services:
  spring-backend:
    build:
      contex: ..
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    networks:
      - app-network

  react-frontend:
    image: node:18-alpine
    working_dir: /workspace/frontend
    volumes:
      - ../frontend:/workspace/frontend:cached
    command: ["npm", "start"]
    ports:
      - "3001:3000"  # Reactのポート変更
    networks:
      - app-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: calmline_db
    ports:
      - "5433:5432"  # PostgreSQLのポート変更
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
